default: &default
      adapter: postgresql
      encoding: unicode
      pool: 5
      username: username
      password: password
      host: localhost

development:
  <<: *default
  database: blog_development

test:
  <<: *default
  database: blog_test

production:
  <<: *default
  host: <%= ENV['IP'] %>
  database: blog_production
